---
name: build static site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          sh rustup.sh -y
          rustup --version

      - name: install and switch to rustup's nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup run nightly rustc --version
          rustup default nightly

      - name: install `wkhtmltopdf` tool
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt install -y ./wkhtmltox_0.12.6-1.focal_amd64.deb

      - name: checkout repository
        uses: actions/checkout@v3

      - name: build and run the program
        run: |
          cargo run --release
          ls -altr

      - name: cleanup
        run: |
          #"echo 'drop: rustup.sh' && rm rustup.sh 2>/dev/null"
          ls

      - name: archive artifact
        shell: bash
        run: >
          tar
          --dereference --hard-dereference
          --directory "$PWD"
          -cvf "$PWD/github-pages"
          --exclude=.git
          --exclude=.github
          --exclude=target
          .

      - name: upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: github-pages

  test:
    # This is jist a stub for future unit/integration tests applied to
    # the binary or generated site itself
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: check the site is ok
        run: |
          curl -L enkron.github.io
          echo "GITHUB_SHA=$GITHUB_SHA"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
